blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/TheHolyOneZ/discord-bot-framework/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Vulnerability
    url: https://github.com/TheHolyOneZ/discord-bot-framework/security/advisories
    about: Report security vulnerabilities privately